config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get "admin" => "admin#index"

  get "product" => "product#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @not_fulfilled_orders = Order.where(fulfilled: false).order(created_at: :asc)
    @fulfilled_orders = Order.where(fulfilled: true).order(created_at: :asc)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_first_name, :customer_last_name, :customer_email, :quantity, :fulfilled, :total, :address)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[show edit update destroy]

  # GET /admin/products or /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @product.update(admin_product_params.reject { |k| k["images"]})
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
      end
    end
    redirect_to admin_products_path, notice: "Product updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end

  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :size, :price, :active, :images)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    @quick_stats = {
      sales: Order.where(created_at: Time.now.midnight..Time.now).count,
      revenue: Order.where(created_at: Time.now.midnight..Time.now).sum(:total)&.round(),
      avg_sale: Order.where(created_at: Time.now.midnight..Time.now).average(:total)&.round(),
      per_sale: OrderProduct.joins(:order).where(orders: { created_at: Time.now.midnight..Time.now })&.average(:quantity)
    }
    @orders_by_day = Order.where('created_at > ?', Time.now - 7.days).order(:created_at)
    @orders_by_day = @orders_by_day.group_by { |order| order.created_at.to_date}
    @revenue_by_day = @orders_by_day.map { |day, orders| [day.strftime("%A"), orders.sum(&:total)] }
    if @revenue_by_day.count < 7
      days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

      data_hash = @revenue_by_day.to_h
      current_day = Date.today.strftime("%A")
      current_day_index = days_of_week.index(current_day)
      next_day_index = (current_day_index + 1) % days_of_week.length

      ordered_days_with_current_last = days_of_week[next_day_index..-1] + days_of_week [0...next_day_index]

      complete_ordered_array_with_current_last = ordered_days_with_current_last.map { |day| [data_hash.fetch(day, 0)] }

      @revenue_by_day = complete_ordered_array_with_current_last
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_products = Product.all
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<h1>Admin Home</h1>

<div class="flex justify-between flex-wrap mt-8 w-full items-center max-w-4xl">
  <h2 class="text-2xl text-gray-800 font-medium mb-4">Daily Stats</h2>
  <div class="flex gap-10 flex-col md:flex-row justify-between w-full">
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl text-white">Revenue</div>
        <p class="text-white text-base">
          £<%= @quick_stats[:revenue] ? (@quick_stats[:revenue]/100.0).to_s : "0" %>
        </p>
      </div>
    </div>

    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl text-white">Total Sales</div>
        <p class="text-white text-base">
          <%= @quick_stats[:sales] ? (@quick_stats[:sales]).to_s : "0" %>
        </p>
      </div>
    </div>

    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl text-white">Average Sale</div>
        <p class="text-white text-base">
          £<%= @quick_stats[:avg_sale] ? (@quick_stats[:avg_sale]/100.0).to_s : "0" %>
        </p>
      </div>
    </div>
  </div>


  <div class="my-8 w-full">
    <h2 class="text-2xl text-gray-800 font-medium mb-4">Revenue</h2>
    <div class="w-full" data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json %>">
      <canvas id="revenueChart"></canvas>
    </div>
  </div>

  <div class="flex flex-col w-full">
    <h2 class="text-2xl text-gray-800 mb-4 font-medium">Recent Unfulfilled Orders</h2>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-gray-100" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Order ID</th>
        <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Customer</th>
        <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Date</th>
        <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Amount</th>
      </thead>
      <tbody class="text-gray-700">
        <% @orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= link_to order.id, [:admin, order], class: "underline" %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.customer_email %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.created_at.strftime("%B %d, %Y %H:%M") %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= (order.total/100.00).to_s%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </div>
  </div>

</div>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer first name:</strong>
    <%= order.customer_first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Customer last name:</strong>
    <%= order.customer_last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= order.quantity %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fulfilled:</strong>
    <%= order.fulfilled %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= order.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

  <% if order.order_products.any? %>
    <strong class="block font-medium mb-1">Products</strong>
    <% order.order_products.each do |op| %>
      <%= op.product.name %>
      <%= op.product.size %>
      <%= op.product.quantity %>
    <% end %>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to "Show this order", [:admin, order], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this order", edit_admin_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Show this order", [:admin, @admin_order], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <h2>Unfulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-o.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflox=x-auto">
          <table class="min-w-full overflow-x-scoll">
            <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Order ID
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Customer e-mail
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Address
              </th>
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Total
              </th>
            </tr>
            </thead>
            <tbody>
              <% @not_fulfilled_orders.each do |o|%>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o] %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    £<%= o.total %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <br>
  <h2>Fulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-o.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflox=x-auto">
          <table class="min-w-full overflow-x-scoll">
            <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Order ID
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Customer e-mail
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Address
              </th>
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Total
              </th>
            </tr>
            </thead>
            <tbody>
              <% @fulfilled_orders.each do |o|%>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o] %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    £<%= o.total %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <h2 class="text-2xl text-gray-800 mb-4 font-medium">Order <%= @admin_order.id %></h2>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_order %>

    <%= link_to "Edit this admin_order", edit_admin_order_path(@admin_order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this admin_order", admin_order_path(@admin_order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to admin_orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Size:</strong>
    <%= product.size %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= product.active %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", [:admin, product], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_admin_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Show this product", [:admin, @admin_product], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_admin_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-o.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflox=x-auto">
          <table class="min-w-full overflow-x-scoll">
            <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Name
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Description
              </th>
            </tr>
            </thead>
            <tbody>
              <% @admin_products.each do |p|%>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= p.image.present? ? image_tag(p.image.variant(:thumb)) : image_tag("https://via.placeholde.com/50") %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to p.name, edit_admin_product_path(p) %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap tex-sm font-medium text-gray-800">
                    <%= p.description %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_product %>

    <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", admin_product_path(@admin_product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<%# Banner %>
<div class="bg-gray-800 text-white text-center py-20">
  <h1 class ="text-5xl font-bold mb-4">Welcome to ZenBar</h1>
  <p class="text-xl mb-8">The best coffee</p>
  <%= link_to "All coffees", root_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded" %>
</div>

<%# Products Sesion %>
<div class="flex flex-wrap justify-center mt-8 items-center gap-10">
  <% @main_products.each do |product| %>
    <%= link_to product_path(product) %>
    <div class="flex flex-col mb-4">
      <h2 class="text-white font-medium text-lg text-center mb-6">
        <%= product.name %>
        <%= product.images.present? ? image_tag(product.images, class: "max-w-lg") : image_tag("https://via.placeholder.com/300") %>
      </h2>
    </div>
  <% end %>
</div>

<%# Testimonials Container %>
<div class="bg-gray-100 py-20 my-10">
  <div class="container mx-auto px-6">
    <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">Customer Testimonials</h2>
    <div class="flex flex-wrap">
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">"I've been djfdf fnfd fn dfnk dfknd fkndf kndfk ndf kdfn kdfn kdfn kdfn kdfnd mff" </p>
          <p class="text-gray-500 text-xs">- Customer one</p>
        </div>
      </div>
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">"I've been djfdf fnfd fn dfnk dfknd fkndf kndfk ndf kdfn kdfn kdfn kdfn kdfnd mff" </p>
          <p class="text-gray-500 text-xs">- Customer two</p>
        </div>
      </div>
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">"I've been djfdf fnfd fn dfnk dfknd fkndf kndfk ndf kdfn kdfn kdfn kdfn kdfnd mff" </p>
          <p class="text-gray-500 text-xs">- Customer three</p>
        </div>
      </div>
    </div>
  </div>
</div>

<%# Newsletter subscibe %>
<div class="bg-gray-500 text-white my-10 text-center py-20">
  <h2 class="text-3xl font-bold mb-6">Stay Updated</h2>
  <p class="mb-8">Subscribe for our newsletter for the latest updates and offers</p>
  <%= form_with url: root_path, method: :post, local: true, class: "flex justify-center" do %>
    <%= email_field_tag :email, nil, placeholder: "Enter your e-mail", class: "p-2 rounded-l text-gray-800" %>
  <%= submit_tag "Subscribe", class: "bg-gray-700 hover:bg-gray-800 cursor-pointer text-white font-bold py-2 px-4 rounded-r" %>
  <% end %>
</div>

<%# Footer %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecomm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
      <nav class="flex">
        <div class="w-64 p-4 h-screen bg-gray-600 sticky top-0">
          <div class="flex">
            <%= image_tag 'coffee.png', class: 'w-16' %>
            <h1 class="text-md py-2 text-gray-50 font-bold hidden md:block">
              Ecomm Admin
            </h1>
          </div>
          <ul class="flex flex-col text-gray-50">
            <li>
              <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <p class="hidden md:inline-block">Dasboard</p>
              <% end %>
            </li>

            <li>
              <%= link_to admin_products_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <p class="hidden md:inline-block">Products</p>
              <% end %>
            </li>

            <li>
              <%= link_to admin_orders_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <p class="hidden md:inline-block">Orders</p>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_admin_session_path, data: {"turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?"}, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <p class="hidden md:inline-block">Sign Out</p>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <div class="w-full p-8">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-gra">

</footer>